config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'home#main'

  resources :products do
    resources :links
    resources :prices, only: :index
  end

  resources :shops, only: :index
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  belongs_to :product
  belongs_to :shop
  has_many :prices, dependent: :destroy

  validates_presence_of :product
end

app/models/price.rb
# frozen_string_literal: true

class Price < ApplicationRecord
  belongs_to :link

  validates_presence_of :link, :value

  before_create :notify_user, if: :goal_reached?

  delegate :product, :shop, to: :link

  private

  def notify_user
    PriceGoalReachedNotificationMailer.fixed_goal(
      product.user,
      product,
      shop.url,
      value
    ).deliver_later
  end

  def goal_reached?
    return if product.settings.nil?

    value <= product.settings.price_limit
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :links, dependent: :destroy
  has_one :settings, class_name: 'Product::Settings'
  belongs_to :user

  validates_presence_of :user

  accepts_nested_attributes_for :settings

  def prices
    Price.where(link: links)
  end
end

app/models/product/settings.rb
# frozen_string_literal: true

class Product
  class Settings < ApplicationRecord
    belongs_to :product
  end
end

app/models/shop.rb
# frozen_string_literal: true

class Shop < ApplicationRecord
  def parse_value_from_html(html_content)
    case name
    when 'Ulmart'
      parse_value_from_ulmart(html_content)
    end
  end

  private

  def parse_value_from_ulmart(html_content)
    price_css_selector = 'section[itemtype="http://schema.org/Product"] meta[itemprop="price"]'

    price_tag = Nokogiri::HTML(html_content).css(price_css_selector)
    price_value = price_tag.attribute('content').value

    price_value.to_f
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products

  def links
    Link.where(product: products)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def main; end
end

app/controllers/links_controller.rb
# frozen_string_literal: true

class LinksController < ApplicationController
  def show
    @link = current_user.links.find(params[:id])
    @product = @link.product
    @shop = @link.shop
    @prices = @link.prices
  end

  def new
    @product = current_user.products.find(params[:product_id])
    @link = current_user.links.new(product: @product)
    @shops = Shop.all
  end

  def create
    link = current_user.links.create(link_params)

    if link.persisted?
      redirect_to product_path(link.product)
    else
      redirect_back
    end
  end

  def destroy
    link = current_user.links.find(params[:id]).destroy

    redirect_to product_path(link.product)
  end

  private

  def link_params
    params.require(:link).permit(:url, :shop_id, :product_id)
  end
end

app/controllers/prices_controller.rb
# frozen_string_literal: true

class PricesController < ApplicationController
  def index
    @show_links_column = true
    @prices = product.prices
  end

  private

  def product
    @product ||= current_user.products.find(params[:product_id])
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :find_product, only: %w[show edit update]

  def index
    @products = product_list
  end

  def show
    @links = @product.links
  end

  def new
    @product = product_list.new
  end

  def create
    product = product_list.create(product_params)

    if product.persisted?
      redirect_to products_path
    else
      redirect_back
    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      redirect_to products_path
    else
      redirect_to edit_product_path(@product)
    end
  end

  def destroy
    product_list.find(params[:id]).destroy

    redirect_to products_path
  end

  private

  def product_list
    current_user.products
  end

  def product_params
    params.require(:product).permit(:name, settings_attributes: [:price_limit])
  end

  def find_product
    @product = product_list.find(params[:id])
  end
end

app/controllers/shops_controller.rb
# frozen_string_literal: true

class ShopsController < ApplicationController
  def index
    @shops = Shop.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/links_helper.rb
# frozen_string_literal: true

module LinksHelper
  def link_title
    @product.name + ' at ' + @shop.name
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/home/main.html.slim
div
  = link_to t('page_titles.products'), products_path
div
  = link_to t('page_titles.shops'), shops_path

app/views/layouts/application.html.slim
doctype html
html lang='ru'
  head
    title = yield(:page_title)
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          = link_to I18n.t('product_name'), root_path, class: 'navbar-brand'
        #navbar.collapse.navbar-collapse
          ul.nav.navbar-nav
            li class=('active' if current_page?(products_path))
              = link_to I18n.t('page_titles.products'), products_path
            li class=('active' if current_page?(shops_path))
              = link_to I18n.t('page_titles.shops'), shops_path
    div.container
      div.page-content
        p.notice = notice
        p.alert = alert
        = yield

app/views/links/new.html.slim
h1 Add new link to product

= form_for @link, {url: product_links_path} do |f|
  = f.label :url
  = f.text_field :url
  = f.label :shop_id
  = f.select :shop_id, @shops.map { |shop| [shop.name, shop.id] }
  = f.hidden_field :product_id
  = f.submit

app/views/links/show.html.slim
- content_for :page_title do
  = link_title
h1 = link_title

= render 'shared/prices_list', prices: @prices

app/views/prices/index.html.slim
- content_for :page_title do
  = t('page_titles.prices')
  | &nbsp;(#{@product.name})

h1 = t('page_titles.prices')

.btn.btn-lg.btn-default
  = link_to t('.to_product'), product_url(@product)

= render 'shared/prices_list', prices: @prices

app/views/products/_product_form.html.slim
= form_for @product do |product_fields|
  = product_fields.label :name
  = product_fields.text_field :name
  = product_fields.fields_for :setting_attributes, product_settings do |settings_fields|
    = settings_fields.label :price_limit
    = settings_fields.number_field :price_limit

  = product_fields.submit

app/views/products/edit.html.slim
h1 Edit product

= render 'product_form', product: @product, product_settings: @product.settings

app/views/products/index.html.slim
- content_for :page_title do
  = t('page_titles.products')

h1 = t('page_titles.products')

form action=new_product_path
  button type="submit" class="btn btn-lg btn-success"
    i.fa.fa-plus-circle aria-hidden="true"
    | &nbsp;
    = t('products.add')


.table-responsive
  table.table.table-striped
    thead
      tr
        th = t('.table_headers.name')
        th width="100px" = t('.table_headers.created_at')
        th width="25px"
        th width="25px"
    - @products.each do |product|
      tr
        td = link_to product.name, product
        td = product.created_at.to_date
        td = link_to product_path(product),
          data: {confirm: t('are_you_sure')},
          method: :delete,
          title: t('.delete') do
          i.fa.fa-trash aria-hidden="true"
        td = link_to edit_product_path(product),
          title: t('.edit') do
          i.fa.fa-edit aria-hidden="true"

app/views/products/new.html.slim
h1 Add new product

= render 'product_form', product: @product, product_settings: @product.build_settings

app/views/products/show.html.slim
- content_for :page_title do
  = t('page_titles.products') + ' || ' + @product.name

h1 = @product.name

#control_panel
  form action=new_product_link_path(@product)
    button type="submit" class="btn btn-lg btn-success"
      i.fa.fa-plus-circle aria-hidden="true"
      | &nbsp;
      = t('links.add')

  .btn.btn-lg.btn-default
    = link_to t('.to_prices_history'), product_prices_url(@product)

p
  | #{t('.price_limit_label')}: #{@product.settings.price_limit}

.table-responsive
  table.table.table-striped
    thead
      tr
        th = t('links.table_headers.name')
        th = t('links.table.shop')
        th width="150px" = t('links.table.created_at')
        th width="50px" = t('links.table.url')
        th width="50px"
    - @links.each do |link|
      tr
        td = link_to link.url, product_link_url(@product, link)
        td = link.shop.name
        td = link.created_at.to_date
        td = link_to '#', link.url, target: '_blank', rel: 'nofollow'
        td = link_to product_link_path(@product, link),
                data: { confirm: t('are_you_sure') },
                method: :delete,
                title: t('links.delete') do
          i.fa.fa-trash aria-hidden="true"

app/views/shared/_prices_list.html.slim
.table-responsive
  table.table.table-striped
    thead
      tr
        - if @show_links_column
          th = t('prices.table_headers.link')
        th = t('prices.table_headers.parced_at')
        th = t('prices.table_headers.value')
    - prices.each do |price|
      tr
        - if @show_links_column
          td = link_to price.link.url, product_link_url(@product, price.link)
        td = price.created_at
        td = price.value || t('prices.nil_value')

app/views/shops/index.html.slim
- content_for :page_title do
  = t('page_titles.products')

h1 = t('page_titles.shops')

.table-responsive
  table.table.table-striped
    thead
      tr
        th = t('shops.table_headers.name')
        th = t('shops.table_headers.url')
        th width="200px" = t('shops.table_headers.created_at')
    - @shops.each do |shop|
      tr
        td = shop.name
        td = link_to shop.url, shop.url
        td = shop.created_at